# Generated by Django 3.0.8 on 2020-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_location', models.CharField(max_length=50)),
                ('contact_notes', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
